export default [
  {
    _id: "Q101",
    title: "Fundamentals of Web Development",
    description: "Test your understanding of basic web development concepts",
    course: "RS101",
    status: "published",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    attempts: 1,
    showCorrectAnswers: "After Submission",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2024-12-29T13:00:00.000Z",
    availableFrom: "2024-08-13T22:00:00.000Z",
    until: "2024-12-15T00:00:00.000Z",
    questions: [
      {
        _id: "Q1011",
        question: "What does HTML stand for?",
        points: 10,
        type: "MULTIPLE_CHOICE",
        options: [
          "Hyper Text Markup Language",
          "High Tech Machine Learning",
          "Hyperlink and Text Management Language",
          "Home Tool Markup Language",
        ],
        correctAnswer: "Hyper Text Markup Language",
      },
      {
        _id: "Q1012",
        question: "CSS is used primarily for:",
        points: 10,
        type: "MULTIPLE_CHOICE",
        options: [
          "Styling",
          "Scripting",
          "Database management",
          "Server configuration",
        ],
        correctAnswer: "Styling",
      },
      {
        _id: "Q1013",
        question: "JavaScript is a client-side programming language.",
        points: 5,
        type: "TRUE_FALSE",
        options: ["True", "False"],
        correctAnswer: "True",
      },
    ],
  },
  {
    _id: "Q102",
    title: "React Components Practice",
    description: "Practice quiz on React components and state management",
    course: "RS101",
    status: "draft",
    quizType: "Practice Quiz",
    assignmentGroup: "Practice",
    shuffleAnswers: false,
    timeLimit: 30,
    multipleAttempts: true,
    attempts: 3,
    showCorrectAnswers: "Immediately",
    accessCode: "REACT2024",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: true,
    dueDate: "2024-12-20T23:59:00.000Z",
    availableFrom: "2024-08-15T00:00:00.000Z",
    until: "2024-12-20T23:59:00.000Z",
    questions: [
      {
        _id: "Q1021",
        question: "What hook is used to manage state in functional components?",
        points: 15,
        type: "FILL_BLANK",
        correctAnswer: "useState",
      },
      {
        _id: "Q1022",
        question: "Which of these is not a React Hook?",
        points: 10,
        type: "MULTIPLE_CHOICE",
        options: ["useEffect", "useState", "useContext", "useComponent"],
        correctAnswer: "useComponent",
      },
      {
        _id: "Q1023",
        question: "React components must return a single root element.",
        points: 5,
        type: "TRUE_FALSE",
        options: ["True", "False"],
        correctAnswer: "True",
      },
    ],
  },
  {
    _id: "Q103",
    title: "Course Feedback Survey",
    description:
      "Please provide your feedback about the Web Development course",
    course: "RS101",
    status: "published",
    quizType: "Ungraded Survey",
    assignmentGroup: "Surveys",
    shuffleAnswers: false,
    timeLimit: 0,
    multipleAttempts: false,
    attempts: 2,
    showCorrectAnswers: "Never",
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2024-12-20T23:59:00.000Z",
    availableFrom: "2024-12-01T00:00:00.000Z",
    until: "2024-12-20T23:59:00.000Z",
    questions: [
      {
        _id: "Q1031",
        question: "How would you rate the course content?",
        points: 0,
        type: "MULTIPLE_CHOICE",
        options: ["Excellent", "Good", "Average", "Needs Improvement"],
        correctAnswer: null,
      },
      {
        _id: "Q1032",
        question: "The pace of the course was appropriate.",
        points: 0,
        type: "TRUE_FALSE",
        options: ["True", "False"],
        correctAnswer: null,
      },
      {
        _id: "Q1033",
        question: "What suggestions do you have for improving the course?",
        points: 0,
        type: "FILL_BLANK",
        correctAnswer: null,
      },
    ],
  },
  {
    _id: "Q101",
    title: "Introduction to course 2",
    description: "A basic quiz covering fundamental concepts in biology.",
    course: "RS102",
    quizStatus: true,
    quizType: "Graded Quiz",
    points: 100,
    assignmentGroup: "Quizzes",
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 2,
    showCorrectAnswers: "After Submission",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2025-12-29T13:00:00Z",
    availableDate: "2024-08-13T22:00:00Z",
    untilDate: "2024-12-15T00:00:00Z",
    questions: [
      {
        _id: "Q1011",
        question: "What is the powerhouse of the cell?",
        options: [
          "Nucleus",
          "Mitochondria",
          "Ribosome",
          "Endoplasmic Reticulum",
        ],
        answer: "Mitochondria",
      },
      {
        _id: "Q1012",
        question: "Which molecule carries genetic information?",
        options: ["DNA", "RNA", "Proteins", "Lipids"],
        answer: "DNA",
      },
      {
        _id: "Q1013",
        question:
          "What process do plants use to convert sunlight into chemical energy?",
        options: [
          "Respiration",
          "Photosynthesis",
          "Transpiration",
          "Fermentation",
        ],
        answer: "Photosynthesis",
      },
    ],
  },
];
